print('Hello! My name is ChatBot')
print('I was created in 2026')
a = input('Pls, remind me your name: \n')
print('What a great name u have, ', a)
print('Let me guess ur age!')
print('Enter reminders of dividing ur age ')
remainder3 = int(input('by 3: '))
remainder5 = int(input('by 5: '))
remainder7 = int(input('by 7: '))
age = (remainder3 * 70 + remainder5 * 21 + remainder7 * 15) % 105
print('your age is', age, 'thats a good time to start programming')